feign:
  client:
    config:
      default:
        readTimeout: '5000'
        connectTimeout: '5000'
        loggerLevel: BASIC
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 130700272776-391q316cfk511ia92c0k09djb38oe78k.apps.googleusercontent.com
  profiles:
    active: dev
refresh-token:
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}

