ACCESS_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/access-token-public.key
REFRESH_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/refresh-token-private.key
ACCESS_TOKEN_PRIVATE_KEY_PATH: access-refresh-token-keys/access-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: access-refresh-token-keys/refresh-token-public.key
logging:
  level:
    org:
      springframework:
        web: trace
      hibernate: error
    com:
      epam:
        esm: debug
  file:
    name: EEJT0003.log
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    password: ${MY_AWS_PASSWORD}
    username: ${MY_AWS_USERNAME}
    url: jdbc:mysql://${MY_AWS_DB_URL}:${MY_DB_PORT}/gifts?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true