/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_project.core;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class UtilsTest {
    @Test
    void shouldReturnTrueWhenPositiveNumber() {
        assertTrue(Utils.isAllPositiveNumbers("31", "43", "1", "0"));
        assertTrue(Utils.isAllPositiveNumbers("12", "13", "99", "21234"));
        assertTrue(Utils.isAllPositiveNumbers("1", "2", "3", "4"));
    }

    @Test
    void shouldReturnFalseWhenAtLeastOneNegativeNumber() {
        assertFalse(Utils.isAllPositiveNumbers("12", "13", "-99", "21234"));
        assertFalse(Utils.isAllPositiveNumbers("-1", "2", "3", "4"));
    }

    @Test
    void shouldReturnFalseWhenAtLeastOneNonNumberChar() {
        assertFalse(Utils.isAllPositiveNumbers("a", "13", "c", "21234"));
        assertFalse(Utils.isAllPositiveNumbers("d", "b", "3", "4"));
    }
}
