/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_project.api;


import multi_project.core.Utils;

public class App {
    public static void main(String[] args) {
        System.out.println(Utils.isAllPositiveNumbers("12", "79"));
        Utils.isAllPositiveNumbers(args);
    }
}
