SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE order_has_certificate RESTART IDENTITY;
TRUNCATE TABLE certificates_has_tags RESTART IDENTITY;
TRUNCATE TABLE certificates RESTART IDENTITY;
TRUNCATE TABLE customer_order RESTART IDENTITY;
TRUNCATE TABLE tags RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY
TRUE;