/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multi_project.api;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void shouldWork() {
        App.main(new String[]{"a", "-13", "14", "."});
    }
}
